### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by Leonidos** [avstaim/LightDI#6]
You use ConcurrentHashMap and locks inside InjectorImpl supposing that LightDI lib is threadsafe. But I noticed that LightDI class is not threadsafe. No guarantee that cuncurrent threads will get same _injector instance. injector IMHO should be threadsafe singleton. Can you clarify this case?

**Comment by avstaim** [comment]
Thank you for your report. Fixed the problem in 954f53dedd1dfa50f68b3584bcfc0b89ca9507ed commit.
